name: chatfinal
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure compatibility with Flutter SDK 3.x

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.0 # Latest compatible version for Firebase Auth
  google_sign_in: ^6.2.0 # Latest compatible version for Google Sign-In
  firebase_core: ^3.11.0 # Latest compatible version for Firebase Core
  cloud_firestore: ^5.6.7 # Latest compatible version for Firestore
  cupertino_icons: ^1.0.8
  firebase_storage: ^12.4.5 # Latest compatible version for Firebase Storage
  image_picker: ^1.1.2 # Latest compatible version for Image Picker
  geolocator: ^14.0.0 # Latest compatible version for Geolocator
  permission_handler: ^12.0.0+1 # Latest compatible version for Permission Handler
  video_player: ^2.5.0 # Added video_player for video previews
  google_maps_flutter: ^2.12.1 # Use an older version if necessary

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Latest compatible version for Flutter Lints

flutter:
  uses-material-design: true
