// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';


// ...


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSgXZssEDhqquvgc8DVEjyIwfekbOTS64',
    appId: '1:298144012264:web:6902db9723a7b0ad57b65d',
    messagingSenderId: '298144012264',
    projectId: 'labchatapp-baa62',
    authDomain: 'labchatapp-baa62.firebaseapp.com',
    databaseURL: 'https://labchatapp-baa62-default-rtdb.firebaseio.com',
    storageBucket: 'labchatapp-baa62.firebasestorage.app',
    measurementId: 'G-B4X8N57S2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq10wxvnT_4wpW5L9QChgWHLE1dyIO3Tw',
    appId: '1:298144012264:android:faddab97b4d4888757b65d',
    messagingSenderId: '298144012264',
    projectId: 'labchatapp-baa62',
    databaseURL: 'https://labchatapp-baa62-default-rtdb.firebaseio.com',
    storageBucket: 'labchatapp-baa62.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDfBcAOKTVbsYM0lQ0aGD2kRpwnGZvU60',
    appId: '1:298144012264:ios:cee1f9e6602da2e857b65d',
    messagingSenderId: '298144012264',
    projectId: 'labchatapp-baa62',
    databaseURL: 'https://labchatapp-baa62-default-rtdb.firebaseio.com',
    storageBucket: 'labchatapp-baa62.firebasestorage.app',
    iosBundleId: 'com.example.chatfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDfBcAOKTVbsYM0lQ0aGD2kRpwnGZvU60',
    appId: '1:298144012264:ios:cee1f9e6602da2e857b65d',
    messagingSenderId: '298144012264',
    projectId: 'labchatapp-baa62',
    databaseURL: 'https://labchatapp-baa62-default-rtdb.firebaseio.com',
    storageBucket: 'labchatapp-baa62.firebasestorage.app',
    iosBundleId: 'com.example.chatfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSgXZssEDhqquvgc8DVEjyIwfekbOTS64',
    appId: '1:298144012264:web:dea22bfe0155de2057b65d',
    messagingSenderId: '298144012264',
    projectId: 'labchatapp-baa62',
    authDomain: 'labchatapp-baa62.firebaseapp.com',
    databaseURL: 'https://labchatapp-baa62-default-rtdb.firebaseio.com',
    storageBucket: 'labchatapp-baa62.firebasestorage.app',
    measurementId: 'G-9NLKQ3WW3W',
  );
}
